apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitraf-core

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: gitraf-core
  app.kubernetes.io/component: git-backend
  app.kubernetes.io/part-of: gitraf
