apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitraf-repos-pvc
  labels:
    app: gitraf-core
    component: git-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: local-path  # Uncomment for k3s default storage class
